name: fardinexpress
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # change_app_package_name: ^1.0.0
  equatable: ^2.0.3
  flutter_bloc: ^7.1.3
  flutter_secure_storage: ^9.2.2
  dio: ^5.3.3
  flutter_dotenv: ^5.0.2
  flutter_easyloading: ^3.0.3
  carousel_slider: ^5.0.0
  get: ^4.6.1
  get_storage: ^2.0.3
  badges: ^3.1.1
  pin_code_fields: ^8.0.1
  # dropdown_search: ^3.0.0
  # flutter_html: ^2.2.1
  flutter_switch: ^0.3.2
  flutter_slidable: ^4.0.0
  image_picker: ^1.0.4
  # google_maps_place_picker: ^2.0.0-nullsafety.3
  # google_maps_place_picker_mb: ^3.0.2
  shimmer: ^3.0.0
  flutter_inappwebview: ^6.1.5
  cached_network_image: ^3.1.0
  # timelines: ^0.1.0
  timelines_plus: ^1.0.6
  pull_to_refresh: ^2.0.0
  flutter_html: ^3.0.0-alpha.5
  flutter_polyline_points: ^2.1.0
  location: ^8.0.0
  flutter_osm_plugin: ^1.3.8
  # deploye version
  # flutter_osm_plugin: ^1.4.1
  extended_image: ^10.0.1
  pointer_interceptor: ^0.10.1+1
  permission_handler: ^11.3.1
  # deploye version
  # permission_handler: ^12.0.0+1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  toggle_switch: ^2.2.2
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  flutter_widget_from_html: ^0.16.0
  rflutter_alert: ^2.0.7
  intl: ^0.20.2
  marquee: ^2.2.3
  webview_flutter_plus: ^0.4.10
  # qr_code_scanner: ^1.0.1
  qr_code_scanner_plus: ^2.0.10+1
  qr_flutter: ^4.1.0
  flutter_svg: ^2.1.0
  url_launcher: ^6.3.0
  awesome_dialog: ^3.2.1
  share_plus: ^10.1.4
  screenshot: ^3.0.0
  app_links: ^6.4.0
  dotted_border: ^3.1.0
  anakut_wallet:
    git:
      url: https://gitlab.com/anakutbank_group/anakut-bank-wallet.git
      ref: development
  change_app_package_name: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  bloc: any
  meta: any
  http: any
  photo_manager: ^3.7.1
  emoji_picker_flutter: ^4.3.0
  file_picker: ^10.2.3
  record: ^6.0.0
  audioplayers: ^6.5.0
  open_file: ^3.5.10
  camera: ^0.11.2
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  chewie: 1.8.5

  # flutter_launcher_name: ^0.0.1
flutter_launcher_name:
  name: "Fardin Express"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/fardin-logo.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/.env
    - assets/lang/
    - assets/img/payment/
    - assets/img/location/
    - assets/img/features/
    - assets/img/background/
    - assets/extend_assets/images/
    - assets/extend_assets/images/payment_service/
    - assets/extend_assets/lang/
    - assets/extend_assets/icons/
    - assets/extend_assets/icons/order_status/
    - assets/extend_assets/icons/payment_method/
    - assets/extend_assets/icons/bottom_navigation/
    - assets/extend_assets/icons/countries/
    - assets/extend_assets/icons/features/
    - assets/extend_assets/svg/
    - assets/icon/
    - assets/illustration/
    - assets/dialog_state/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    - family: Siemreap
      fonts:
        - asset: assets/fonts/Siemreap-Regular.ttf
          # - asset: fonts/TrajanPro_Bold.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
